# Generated by Django 3.2.25 on 2026-06-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('ui', 'UI / Design'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('content', 'Content Feedback'), ('general', 'General Review')], default='general', max_length=20)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('text', models.TextField()),
                ('helpful', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('team_reply', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
