# Generated by Django 3.2.25 on 2026-06-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('healthcare', 'Healthcare'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('water', 'Water & Sanitation'), ('safety', 'Safety'), ('environment', 'Environment'), ('disaster', 'Disaster Relief'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'Under Review'), ('funded', 'Funded'), ('progress', 'In Progress'), ('done', 'Completed'), ('urgent', 'Urgent')], default='review', max_length=20)),
                ('fund_goal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fund_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('votes', models.IntegerField(default=0)),
                ('submitted_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
            },
        ),
    ]
