# Generated by Django 3.2.25 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit (In)'), ('debit', 'Debit (Out)')], max_length=10)),
                ('category', models.CharField(choices=[('government', 'Government'), ('donation', 'Donation'), ('corporate', 'Corporate'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('disaster', 'Disaster Relief'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('received', 'Received'), ('completed', 'Completed'), ('progress', 'In Progress'), ('voting', 'Voting')], max_length=20)),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
